// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkgqbuxdoukjesajnbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZ3FidXhkb3VramVzYWpuYmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjUxMzAsImV4cCI6MjA2MDUwMTEzMH0.rkzgDpqpChIEgXR-boP_rWlDOhF2YFuMReZQURMlXGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);